-- =========================================================================
-- Supabase Table Schema Setup for Raja Rajeshwara Engineerings
-- Run this script in your Supabase project's SQL Editor (https://supabase.com)
-- =========================================================================

-- 1. Create the missing "users" table
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    salt text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Ensure RLS (Row Level Security) is disabled or has appropriate insert/select policies
-- To allow public signup and logins, we can add permissive RLS policies:
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert to users table" 
ON public.users 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow public select from users table" 
ON public.users 
FOR SELECT 
USING (true);
